//Even Fibonacci numbers
//
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
//By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//find the sum of the even-valued terms.

#include <stdio.h>

int main()
{
    int temp = 0; int sum = 0;
    int prev = 1; int c = 1; 
    while (c < 4000000) {
        if (c + prev > 4000000) {
            break;
        }

        temp = c;
        c = c + prev;
        prev = temp;
        
        if (c % 2 == 0) {
            sum += c;  
        }     
    }
    printf("%d\n", sum); 
    printf("%d ", c);
}